# .github/workflows/ci.yml
name: Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-mock pytest-cov pytest-asyncio aiohttp 
        weakref tracemalloc timeit flake8 pylint isort

    - name: Run tests with coverage
      run: |
        pytest --cov=01 --cov-report=xml 01/test_predict.py
        pytest --cov=01 --cov-report=xml 01/test_generator.py
        pytest --cov=02 --cov-report=xml 02/test_process_json.py
        pytest --cov=02 --cov-report=xml 02/test_decorator.py
        pytest --cov=03 --cov-report=xml 03/test_custom_list.py
        pytest --cov=04 --cov-report=xml 04/test_descriptor.py
        pytest --cov=04 --cov-report=xml 04/test_metaclass.py
        pytest --cov=05 --cov-report=xml 05/test_lru_cache.py
        pytest --cov=06 --cov-report=xml 06/test_client.py
        pytest --cov=06 --cov-report=xml 06/test_server.py
        pytest --cov=06 --cov-report=xml 06/test_integration.py
        pytest --cov=07 --cov-report=xml 07/test_fetcher.py
        pytest --cov=08 --cov-report=xml 07/test_classes.py

    - name: Run isort
      run: |
        isort --check --diff 05/
        isort --check --diff 06/
        isort --check --diff 07/
        isort --check --diff 08/

    - name: Run flake8
      run: |
        flake8 01/ --config=.flake8
        flake8 02/ --config=.flake8
        flake8 03/ --config=.flake8
        flake8 04/ --config=.flake8
        flake8 05/ --config=.flake8
        flake8 06/ --config=.flake8
        flake8 07/ --config=.flake8
        flake8 08/ --config=.flake8

    - name: Run pylint
      run: |
        pylint 01/ --rcfile=pylintrc
        pylint 02/ --rcfile=pylintrc
        pylint 03/ --rcfile=pylintrc
        pylint 04/ --rcfile=pylintrc
        pylint 05/ --rcfile=pylintrc
        pylint 06/ --rcfile=pylintrc
        pylint 07/ --rcfile=pylintrc
        pylint 08/ --rcfile=pylintrc

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
