name: Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install unittest # or any testing library
        if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
    - name: Run unittests
      run: |
        cd 01 # Change directory to 01
        python -m unittest discover -s tests -p "*_test.py"
