# .github/workflows/ci.yml
name: Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov flake8 pylint

    - name: Run tests with coverage
      run: |
        pytest --cov=01 --cov-report=xml 01/test_predict.py

    - name: Run flake8
      run: |
        flake8 01/ --config=.flake8

    - name: Run pylint
      run: |
        pylint 01/ --rcfile=.pylintrc

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
